# Generated by Django 6.0 on 2026-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_category_options_note_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Жінка'), ('M', 'Чоловік'), ('NA', 'Не вказано')], max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
